tiny x;
small y;
medium a;
large z;
A = 5;
B = A ADD 7 MUL OPENPAREN C DIV 9 CLOSEPAREN;
Z = 7 ADD 7 ADD 7 ADD 7 MUL;
COND A GTE 5:
REPEAT OPENPAREN A ADD 12 CLOSEPAREN LT OPENPAREN B SUB 7 CLOSEPAREN:
COND B EQ OPENPAREN 5 ADD 7 CLOSEPAREN CLOSEPAREN:
